apiVersion: v1
data:
  admin.enabled: "true"
  exec.enabled: "false"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
